--INSERT INTO EMPLOYEE VALUES (1,'Delhi', 110001);  
INSERT INTO BOOK VALUES ('B1','Author CP',5,'JAVA',5);
INSERT INTO BOOK VALUES ('B2','Author CP',5,'C++',5);
INSERT INTO BOOK VALUES ('B3','Author P',5,'Python',5);

--INSERT INTO SUBSCRIPTION VALUES ('name','B1','2021-12-03',null);